globus/globus-automate-client

- .gitignore
- globus_automate_client/flows_schema.json
The schema specified only an object rather than array of objects.
> Incorrect schema for Action Catch

- docs/source/using_cli_and_flows.rst
- examples/flows/hello-world/definition.json
- globus_automate_client/cli/flows.py
- globus_automate_client/flows_client.py
- Fixes a malformed JSON document that wasn't rendering correctly on readthedocs
- Updates a key in an example
- Updates CLI command descriptions
> A few corrections to docs and the CLI interface

- docs/source/globus_action_providers.rst
- examples/action_bodies/delete_permission.json
- examples/action_bodies/set_permission.json
- examples/action_bodies/update_permission.json
Includes new examples for the various types of permission updates in
the action_bodies directory.
> Update some docs related to the set permissions update

- globus_automate_client/__init__.py
- poetry.lock
- pyproject.toml
> Version bumps and package updates

- globus_automate_client/token_management.py
- poetry.lock
- pyproject.toml
Removes custom SSH session detection in favor of native login's built in detection to determine whether or not it makes sense to launch an browser based login flow.
> Updates fair-research native-login package

- README.rst
- docs/source/python_sdk.rst
- globus_automate_client/__init__.py
- globus_automate_client/action_client.py
- globus_automate_client/cli/actions.py
- globus_automate_client/cli/flows.py
- globus_automate_client/client_helpers.py
- globus_automate_client/flows_client.py
- globus_automate_client/token_management.py
- Decouples the SDK from the CLI via kwargs and callbacks
- create_*_client helper functions are removed from the SDK layer
- Added new_client classmethod to Client classes
> Initial implementation for supporting user supplied authorizers

- examples/flows/transfer-mv/definition.json
- examples/flows/transfer-mv/input_schema.json
- examples/flows/transfer-mv/sample_input.json
This adds an example of a flow that performs a move operation. We will
expect to deploy and maintain this flow for use by customers, but it
also provides an example of flow definition including an input
schema.
> A flow for performing a move operation

- globus_automate_client/action_client.py
- globus_automate_client/cli/flows.py
- globus_automate_client/flows_client.py
Adds Flows support for Flows pagination in a few places:
- List Flows
- Flow Action Log -> This one will work once we get pagination working on the Flow's side
- Flow Action List
- ActionClient.log method
> Exposes Flows service pagination to CLI and SDK

- globus_automate_client/__init__.py
- globus_automate_client/action_client.py
- globus_automate_client/flows_client.py
- poetry.lock
- pyproject.toml
- Increases version number
- Updates dependencies
- Adds marker and per_page parameter documentation
> Updates preparing for release

- globus_automate_client/action_client.py
- globus_automate_client/cli/actions.py
- globus_automate_client/cli/flows.py
Would appreciate a pointer to where in the docs this should be included (if at all—I couldn't find anything similar with `--format` or `--input`)
> Add label argument to flow run

- globus_automate_client/__init__.py
- globus_automate_client/client_helpers.py
- globus_automate_client/flows_client.py
- poetry.lock
- pyproject.toml
Make the flow validation function visible at the top level, and provide the default CLIENT_ID for flow client creation
> Export flow validation function

- globus_automate_client/cli/actions.py
- globus_automate_client/cli/constants.py
- globus_automate_client/cli/flows.py
- globus_automate_client/cli/helpers.py
- globus_automate_client/cli/rich_rendering.py
- poetry.lock
- pyproject.toml
Adds the --watch/-w flag to provide tail-like functionality on Action state reporting endpoints.
- `action run`, `action status`, `flow run,` `flow action-status` and `flow action-log` operations are supported.
Demo: 
https://user-images.githubusercontent.com/62311618/109884730-0e547080-7c43-11eb-9009-0f6eaed57565.mov
> Implements streaming updates for an Action's state

- globus_automate_client/cli/helpers.py
- globus_automate_client/flows_client.py
- Adds more separation between verbose and regular output
- Colorizes verbose output separately
- Outputs verbose output to stderr
- Omits orderings qarg if not set
- Defaults optional args in list_flow_actions to None.
> Various bugfixes + output formatting updates

- globus_automate_client/cli/flows.py
- globus_automate_client/flows_client.py
This is a parameter on a flow, so added to deploy and update of a Flow both in the SDK and CLI layers.
> Add subscription-id support

- globus_automate_client/__init__.py
- poetry.lock
- pyproject.toml
> Updates for release

- docs/source/authoring_flows.rst
- docs/source/conf.py
- docs/source/globus_action_providers.rst
- docs/source/index.rst
- examples/cli/actions.sh
- examples/cli/run_hello_world.sh
Fixes some build errors, adds runnable example to Hello World AP description
> Docs cleanup

- globus_automate_client/client_helpers.py
Users wanting to simply provide their own `http_timeouts` on clients were unable to use the `create_flows_client` helper method and had to resort to custom creating clients via FlowsClient.new_client() which involved distinct package imports and figuring out what the valid defaults were.
This PR allows full customization of the underlying FlowsClient via keyword-only arguments to `create_flows_client`.
> Refactors create_flows_client

- globus_automate_client/cli/auth.py
Cleans up the handling of the logout and revoke operations in multiple
environments. Each of these will only change the tokens stored for the
environment set by GLOBUS_SDK_ENVIRONMENT.
> Cleanup logout/revoke multi-environment

- docs/source/cli_docs.rst
- docs/source/code_snippets/premade_authorizers.py
- examples/sdk_scripts/flow_deploy_and_run.py
- globus_automate_client/flows_client.py
- Updates sample script for creating a FlowsClient
- Adds `label` field to FlowsClient autodoc
- Rebuilds CLI docs with new commands + options
> Various package and doc improvements

- Makefile
- docs/source/authoring_flows.rst
- docs/source/cli_docs.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/license.rst
- docs/source/overview.rst
- globus_automate_client/__init__.py
- globus_automate_client/action_client.py
- globus_automate_client/cli/callbacks.py
- globus_automate_client/cli/flows.py
- globus_automate_client/cli/helpers.py
- globus_automate_client/flows_client.py
- globus_automate_client/helpers.py
- poetry.lock
- pyproject.toml
Some of these include:
- Renaming of role values and migration of filtering to filter_role
instead of filter_roles (plural). Impacts both SDK and CLI.
- Update documentation to talk about different roles, and also
alternative methods of specifying values in expressions and the new
method of catching timeouts.
- Where identities are entered for roles, allow the Globus Auth
username to be used in place of the full urn with uuid. Thus,
john_doe@state.edu could be used to specify a user with a role rather
than using the UUID. Docs updated to guide people as such.
- A few other cleanups here and there.
> Updates to match Flows service updates

- examples/flows/hello-world/definition.json
- examples/flows/hello-world/input-schema.json
- examples/flows/hello-world/input.json
This updates the example to match the action schema
> fix: change hello_world parameter sleep -> sleep_timer

- changelog.d/20211101_121713_jimPruyne_collection_mkdir_aps_expression_functions.rst
- docs/source/authoring_flows.rst
- docs/source/cli_docs.rst
- docs/source/globus_action_providers.rst
- examples/action_bodies/mkdir.json
- poetry.lock
We add docs related to:
- The Collection info AP
- The make directory AP
- The updates to the ls AP
- That there are functions which can be invoked within expressions,
and the following functions:
- `getattr`
- `is_present`
- `pathsplit`
> Adds docs on new APs and expression functions

- changelog.d/20211029_162341_kurtmckee_bugs.rst
- globus_automate_client/flows_client.py
From the changelog fragment:
Bugfixes
--------
-   Fix a bug that prevented the Flows client from properly validating flow definition states in lists.
-   Prevent empty values from appearing in query parameters or JSON submissions.
-   Fix a bug that prevented the input schema of an existing Flow from being set to an all-permissive JSON schema.
-   Fix a bug that prevented a custom authorizer from being used if attempting to list all runs of a specific flow without specifying the flow ID.
-   Fix a bug that introduced duplicate forward slashes in some API URL's.
> Fix some bugs

- .github/workflows/quality.yaml
- .pre-commit-config.yaml
- changelog.d/20211118_180000_kurtmckee_test_and_lint.rst
- docs/source/code_snippets/premade_authorizers.py
- globus_automate_client/action_client.py
- globus_automate_client/cli/actions.py
- globus_automate_client/cli/auth.py
- globus_automate_client/cli/callbacks.py
- globus_automate_client/cli/constants.py
- globus_automate_client/cli/flows.py
- globus_automate_client/cli/helpers.py
- globus_automate_client/cli/main.py
- globus_automate_client/cli/rich_helpers.py
- globus_automate_client/client_helpers.py
- globus_automate_client/flows_client.py
- globus_automate_client/graphviz_rendering.py
- globus_automate_client/helpers.py
- globus_automate_client/queues_client.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_action_client.py
- tests/test_flows_client.py
- tests/test_helpers.py
- tests/test_init.py
- tests/test_sdk_v3.py
- tox.ini
This is the final PR of the original SDK v3 branch. It adds unit testing, linting, and pre-commit hooks. The tests are not yet comprehensive but increase code and branch coverage to nearly 100% for the files they test.
@rudyardrichter I rebased many of the original incremental commits into much broader batches (like grouping most of the file-by-file tests together). Please let me know if this would benefit from further rebasing.
Bugfixes
--------
-   Fix a bug that could allow the Flows authorizer to be lost if an exception was raised.
(Authorizer swaps are now handled using a context manager.)
Other
-----
-   Add code linting, documentation build testing, and a bunch of unit tests.
-   Add GitHub Actions to run on push and pull requests.
-   Add a pre-commit configuration file to …
> Add testing and linting

- changelog.d/20211202_152823_kurtmckee_fix_key_error_sc_12117.rst
- globus_automate_client/cli/helpers.py
> Fix a KeyError crash that occurs when `-v` is passed

- changelog.d/20211209_145022_kurtmckee_fix_flow_display_crash_sc_12186.rst
- globus_automate_client/cli/flows.py
- globus_automate_client/cli/rich_helpers.py
Closes #110
Thanks to David Kelly for reporting this!
> Fix a ValueError crash when displaying a flow

- CHANGELOG.rst
- changelog.d/20211202_152823_kurtmckee_fix_key_error_sc_12117.rst
- changelog.d/20211209_145022_kurtmckee_fix_flow_display_crash_sc_12186.rst
- pyproject.toml
> Update project metadata for 0.13.0b2

- docs/source/authoring_flows.rst
Exactly what it says on the tin.
> Fix a typo in the docs that affected rendering

- poetry.lock
For more information, see:
* [CVE-2022-24758](https://nvd.nist.gov/vuln/detail/CVE-2022-24758)
> Update `notebook`, which is a dev dependency

- Makefile
- changelog.d/20220405_164819_kurtmckee_flow_loop_examples_sc_13642.rst
- docs/source/cli_docs.rst
- docs/source/example_flows.rst
- examples/flows/loop-a-set-number-of-times/definition.yaml
- examples/flows/loop-with-batch-processing/definition.yaml
> ## NOTE:
>
> This PR also updates the auto-generated CLI documentation, which was not previously done.
> In the future we should set up a pre-commit hook to ensure the docs are always auto-generated.
>
Documentation
-------------
-   [\[sc-13642\]](https://app.shortcut.com/globus/story/13642)    Provide two types of looping in flow definitions:
*   How to loop a set number of times
*   How to perform batch processing over an unknown quantity of items
> Demonstrate looping in flows

- CHANGELOG.rst
- changelog.d/20220429_170559_kurtmckee_update_rich.rst
- pyproject.toml
This release adds a changelog entry regarding the update to rich.
> Release 0.15.0.post1

- changelog.d/20220713_181439_kurtmckee_doc_auto_flow_starts_sc_16711.rst
- docs/source/automating-flow-runs.rst
- docs/source/code_snippets/runner.py
- docs/source/code_snippets/runner.sh
- docs/source/code_snippets/watchmedo.sh
- docs/source/index.rst
Documentation
-------------
-   [[sc-16711]](https://app.shortcut.com/globus/story/16711)     Document how to automatically run a flow based on filesystem change events.
> Document how to auto-run flows by monitoring filesystem events

- .github/workflows/has_changelog.yaml
Exactly what it says on the tin.
> Migrate `has-changelog` action to point at Globus SDK repo

- docs/source/authoring_flows.rst
Exactly what it says on the tin.
> Fix syntax errors in JSON examples in the documentation

- .pre-commit-config.yaml
- globus_automate_client/flows_client.py
Exactly what it says on the tin.
> Update pre commit hooks

- .github/workflows/build.yaml
This fixes an oversight introduced by recent changes to the `tox.ini` file.
> Fix linting in CI
