globus/globus-automate-client

globus_automate_client/action_client.py
globus_automate_client/cli/actions.py

Adds support for creating the full ActionRequest document to the SDK and CLI. 
Previously, when launching an Action, the only parameters that could be set on it were `request_id` and `body`. The full Action Request spec outlines that a `POST` to `/run` may also contain `manage_by` and `monitor_by` fields. Not specifying these was fine but it meant that if someone ever wanted to set/use them, they'd be unable to via the client. This change corrects that. 
[ch2113]

Supports a full ActionRequest via command line/SDK

---

globus_automate_client/cli/queues.py
globus_automate_client/queues_client.py

- Forces the CLI to behave more similarly to the Queues API -- the full Queues object's fields must be provided
- Adds a `typer.Option` supporting `required_timeout`
- Fixes the `body` payload to include the updated queue's id
[ch2381]

Fixes the update queue operation in the CLI and SDK

---

examples/flows/multi-transfer/input_schema.json

A simple schema for this Flow. Can be specified when deploying using the --input-schema option on the CLI.

An input schema for the multi-transfer flow example

---

globus_automate_client/flows_client.py

The code didn't properly handle lists/arrays in the flow
definition (notably on `ErrorEquals` on a `Catch`).
Needed a check that the key being inspected is in the desired key set
before adding the array values into the return set.

Error on traversing flow definition for state names

---

globus_automate_client/action_client.py
globus_automate_client/cli/actions.py

jgaff reported that when using the SDK's `ActionClient` against the [now old] Datacite AP, he would get errors back indicating that  `monitor_by` and `manage_by` cannot be None. What happened is that the SDK would use `None` for `monitor_by` and `manage_by` if no value was supplied, which resulted in action-run requests being sent with those fields set to `None`.  At the AP, these action-run requests would be rejected bc the `ActionRequest` schema expects `monitor_by` and `manage_by` to be lists if they're set.
The fix is to simply remove False'y values from the action-run body before it get's sent to an AP. Because `monitor_by` and `manage_by` are optional, this will allow users to use the SDK's `ActionClient` without specifying values for those args.

Removes False-y values from action_run body

---

globus_automate_client/cli/actions.py
globus_automate_client/cli/callbacks.py
globus_automate_client/cli/flows.py
globus_automate_client/cli/queues.py

This fix essentially adds a second principal validator callback that accepts "public" and a third principal validator callback that accepts "all_authenticated_users" as valid values. These new callbacks use the old callback for validation if the principal is not one of the special values. [ch3716]

Allows special values in principal validation

---

globus_automate_client/flows_schema.json

Make Parameters or InputPath ok, but also allow for neither by
using a slightly new version of the existing Parameters or InputPath
definition that does not include any `required` values.
[ch3823]

Change schema for the Pass State

---

globus_automate_client/cli/queues.py
globus_automate_client/queues_client.py

When using the Queues service, a user needs to acknowledge (aka delete) that a message has been processed before the message is removed. If the message is not deleted, the Queue will place the message back at the head of the Queue where the message will once again be retrieved. At present, the CLI and SDK do not support the deletion action which makes it impossible for users to consume from a Queue to process work. This PR adds functionality at the SDK and CLI level supporting message deletion.
This PR also updates the help string on a Queue's `delivery_timeout` parameter. Essentially, this parameter controls how long the Queue waits for a message-deletion before assuming processing has failed and re-adding the message to the head of the Queue. There's work being done on the Queues …

Adds support for deleting-messages that have been processed

---

docs/source/code_snippets/create_action_client.py
docs/source/code_snippets/create_flows_client.py
docs/source/code_snippets/premade_authorizers.py
docs/source/python_sdk.rst

There have been a few questions about how to use the SDK with pre-existing tokens/Authorizers. This PR contains documentation and examples on how the different ways of doing that with ActionClients and FlowsClients. Once merged, these documents will be automatically displayed on our [readthedocs](https://globus-automate-client.readthedocs.io/en/latest/python_sdk.html) site under the SDK section.

Improves docs on manually pre-created authorizers for Clients

---

globus_automate_client/cli/helpers.py

Found a bug I introduced while deploying the secure egress prototype.

process_input should not try to load arguments that are None

---

globus_automate_client/cli/actions.py
globus_automate_client/cli/constants.py
globus_automate_client/cli/flows.py
globus_automate_client/cli/helpers.py
globus_automate_client/token_management.py

- Ignores exceptions thrown when trying to auto-introspect an AP.  The errors will be explicitly thrown when trying to use the created `ActionClient`
- Supports `GlobusAPIErrors` in printing functions
- Request details now print to `stderr` so that tools like `jq` can parse command output when the `verbosity` flag is set

Adds exception handling to the CLI layer

---

globus_automate_client/cli/actions.py
globus_automate_client/cli/callbacks.py
globus_automate_client/cli/constants.py
globus_automate_client/cli/flows.py
globus_automate_client/cli/helpers.py
globus_automate_client/cli/queues.py
globus_automate_client/token_management.py

When reading input from the user, the CLI determines if the input is a file _first_ by doing filesystem checks. If it is a valid file, we load the file's contents; if it is not a valid file, we use the input as the content directly. When providing JSON directly on the command line, it is very easy to create a long-enough JSON string that triggers a filename too long error. This PR essentially loads the input as content whenever a filename too long error occurs.
This PR builds off the [Adds exception handling to the CLI layer](https://github.com/globus/globus-automate-client/pull/38) PR

Fixes filename too long errors when reading JSON directly from the command line input

---

examples/flows/complex-hello-world/definition.json
examples/flows/hello-plus-transfer/definition.json
examples/flows/hello-world-run-as/definition.json
examples/flows/hello-world-yaml/definition.yaml
examples/flows/hello-world/definition.json
examples/flows/multi-transfer/definition.json
examples/flows/notify-of-options-and-report/definition.json
examples/flows/send-notification/definition.json
examples/flows/single-delete/definition.json
examples/flows/single-transfer/definition.json
examples/flows/web-option-with-parameters/definition.json
examples/flows/web-option/definition.json

Including the scope in the flow definition is an anti-pattern at this
point because introspection by the Flows service does a better job.
Also, seems my editor settings have changed since last I visited these
files and indent size has shrunk, likely making for any ugly
diff. Sorry, but I guess since I prefer the 2 space indent it is
better in the long run.

Remove ActionScope from example flows

---

globus_automate_client/cli/flows.py
globus_automate_client/cli/helpers.py
globus_automate_client/flows_client.py

Adds support in the CLI and SDK for the new filtering/ordering options available on the Flow List and Flow Action List endpoints and it's corresponding usage documentation. 
In the SDK, the general approach is to accept a series of filters/ordering options as dictionaries which get mapped to query parameters sent off to the Flows service.
In the CLI, I added fairly generic `--filter` and `--orderby` which accept `key=value` formatted strings. I think this is the most generalizable way of supporting adhoc options as they change or get updated on the server. There's still the issue of where a user should look to find which fields support filtering and ordering. I think I'd rather keep that information out of the CLI for now and bank on some Flows documentation providing that information.

Adds Filtering and Ordering on Flow List and Flow Action List

---

Makefile
docs/source/index.rst
docs/source/quick_start.rst
docs/source/using_cli_and_flows.rst
globus_automate_client/action_client.py
globus_automate_client/cli/actions.py
globus_automate_client/cli/auth.py
globus_automate_client/cli/flows.py
globus_automate_client/cli/rich_rendering.py
globus_automate_client/client_helpers.py
globus_automate_client/flows_client.py

I started updating the docs but realized it would be more effort than I thought it would be. This PR address some concerns around what exactly an acceptable principal value is, both in the `CLI` and `SDK` levels for `ActionClients` and `FlowsClients`. It also explicitly adds the `manage_by` and `monitor_by` arguments to the `FlowClient.run()` method for better visibility (they used to just be lumped into `kwargs` and passed onto the underlying `ActionClient.run()` call).
Also:
- Fixes bugs in live rendering where Globus Auth logins weren't displaying correctly when watching an executing Action.
- Updates `flow lint` output to clearly indicate the linting results, instead of outputting Flow definitions.
- Adds support to `flow display` for visualizing local or remote Flow definitions.
- …

Adds documentation around monitor_by and manage_by

---

globus_automate_client/cli/auth.py

Inspired by announcements related to Search client which may also
impact other uses of the globus sdk tokenstore (which maybe should
include this client at some point as well).

Set tokenfile to R/W by owner only

---

globus_automate_client/cli/flows.py

When deploying a Flow, the output formatting would JSON/YAML dump without any indentation, resulting in a hard to deal with blob. This PR adds the indentation back into the command output.

Fixes formatting issue on Flow deploys

---

pyproject.toml

This PR adds license info to the output of the `pip show globus-automate-client` command:
Before:
```
Name: globus-automate-client
Version: 0.11.4
Summary: Experimental client for the in-development Globus Automate services
Home-page: None
Author: Jim Pruyne
Author-email: pruyne@globus.org
License: None
Location: /usr/local/lib/python3.6/site-packages
Requires: typer, jsonschema, rich, globus-sdk, PyYAML, graphviz
Required-by:
```
After:
```
Name: globus-automate-client
Version: 0.11.4
Summary: Experimental client for the in-development Globus Automate services
Home-page: None
Author: Jim Pruyne
Author-email: pruyne@globus.org
License: Apache-2.0
Location: /Users/uriel/Projects/github.com/globus/globus-automate-client/.venv/lib/python3.6/site-packages
Requires: globus-sdk, jsonschema, …
```

Add license to output of pip show

---

globus_automate_client/cli/flows.py

It's happened often enough where CLI users are confused why they get different Flow output on the Flow List command. This PR removes the default role filtering (used to default to created_by) so that if the CLI command is run without any role filters, the results returned are dependent on the API.

Flows List default roles are Flows API default roles

---

globus_automate_client/flows_client.py

Updates the `get_flow` SDK method to use the `/flows/flow_id` API route rather than `/flow_id`.

Refactor the SDK to use the preferred API routes

---

docs/source/authoring_flows.rst

This PR updates the Flows docs to reference `run_id` in the pre-populated run-time state rather than `action_id`. Users already using `action_id` should still be able to use it (it still works) but these docs will encourage users writing Flows to reference `run_id` instead.
[ch9121]

Updates the docs to use Run ID

---

globus_automate_client/cli/auth.py
globus_automate_client/flows_client.py

This PR fixes a bug in `action_enumeration` in the SDK. When making the call, the FlowsClient would make the call using the management authorizer, which was typically the authorizer with consents to the MANGE_FLOWS scope: `https://auth.globus.org/scopes/eec9b274-0c81-4334-bdc2-54e90e689b9a/manage_flows`). It should have been making the call using an authorizer with consents to the RUN_STATUS scope: `https://auth.globus.org/scopes/eec9b274-0c81-4334-bdc2-54e90e689b9a/run_status`. 
This wasn't an issue at the CLI level because the CLI would instantiate the FlowsClient where the management authorizer was an authorizer with consents to the RUN_STATUS scope rather than to the MANAGE_FLOWS scope. That meant that the CLI level FlowsClient could only be used to enumerate actions and would fail on …

Fixes action_enumeration at the SDK level

---

examples/flows/hello-consent/definition.json
examples/flows/hello-consent/schema.json
globus_automate_client/cli/actions.py
globus_automate_client/cli/callbacks.py
globus_automate_client/cli/constants.py
globus_automate_client/cli/flows.py
globus_automate_client/cli/helpers.py
globus_automate_client/cli/main.py
globus_automate_client/cli/queues.py
globus_automate_client/cli/rich_helpers.py
globus_automate_client/cli/rich_rendering.py
globus_automate_client/client_helpers.py
globus_automate_client/flows_client.py
globus_automate_client/queues_client.py
poetry.lock
pyproject.toml

This PR adds support for displaying list data as tabular output [see screenshots below]. Notice that the tabular outputs play well with the other options available on the CLI such as filtering, verbose output, and watching for updates. Only a subset of the API's returned data gets formatted as a table due to the limits of a terminal window but the fields we display can be tweaked (or processed as in the case of the datetime fields in the screenshots). For the full data to be parsed, the output needs to be formatted as either JSON or YAML. On all commands, if the output is specified as JSON, external tools (like JQ) can parse the output and pull specific fields if needed.
The general approach was to separate the `Result` and `Renderer` into distinct objects, and then manage both via a …

Unifies CLI output display and adds tabular display

---

docs/source/authoring_flows.rst
docs/source/cli_docs.rst
docs/source/example_flows.rst
docs/source/index.rst
examples/flows/failed-consent/definition.yaml
examples/flows/failed-consent/schema.yaml
globus_automate_client/flows_schema.json

This PR:
- Updates the local copy of the Flows service OpenAPI spec to include the new Fail state
- Adds a new example Flow [failed-consent] to demonstrate how you can plug a Fail state into a Flow definition
- Updates the CLI documentation (it had been a while since we did this)
- Updates docs to reference supporting the new Fail state
- Adds a page to the docs that links to our GH repo flow examples

Client updates to allow Fail states in Flows

---

.github/workflows/has_changelog.yaml

Per our discussion a while ago, this is a simple workflow to check for the addition of changelog fragments in a PR, or else a PR label (which I added for this one).
Here we're checking for `*.rst` files specifically, but honestly it could just be any new files in `changelog.d` which might make it easier to duplicate for other repositories, though easier to miss if someone accidentally creates a fragment in the wrong format.

Add workflow to check for changelog fragments

---

changelog.d/20211116_163321_uriel_allow_empty_flow_updates.rst
globus_automate_client/flows_client.py

This PR adds logic to the `FlowsClient`'s `update_flow` method to differentiate between updates that set fields to empty objects and updates that are not setting fields at all. Fields now default to `None` and if they are set to non-`None` values they are carried over into the API request. What this allows the SDK to do is to empty out role-based access control (RBAC) lists and set text fields to empty strings (note that the API technically doesn't disallow empty strings).

Allows empty strings and lists in update_flow

---

changelog.d/20211123_092348_kurtmckee_merge_parameter_aliases_better.rst
globus_automate_client/action_client.py
globus_automate_client/flows_client.py
globus_automate_client/helpers.py

This change simplifies the code in the `merge_aliases()` function and allows it to merge additional value types, like strings and tuples of strings.
Bugfixes
--------
-   Support strings (and tuples/sets containing strings) as argument values
when running, deploying, or updating an action or a flow and specifying
a keyword argument alias like ``visible_to`` or ``runnable_by``.
[sc-11808]

Allow more value types when merging keyword parameter aliases

---

.github/workflows/has_changelog.yaml

This PR adds a the `workflow` call event as a trigger which is necessary to allow other Github Action workflows to use the workflow. This is a stop gap solution to share the enforce changelog fragment behavior across our repositories until something more permanent gets set up.

Allows workflow to be reused

---

WORKFLOW.md

I'm basing this document heavily off of the document that Kurt has been writing up in our service repositories. The biggest differences are that I've added references (where appropriate) to ReadTheDocs, removed the release script, made references to when and where to create PRs during the release process, and filled in the `Deploying to production` section with a reference to a currently non-existent Github Action.
The end goal is to have a workflow here that is very similar to our service repos. This process is what I had in mind when making my comments on PR-251 in Flows. I'm hoping we can compare and make updates to both PRs so that we're happy with the workflow.

Adds WORKFLOW.md file

---

changelog.d/20211214_142801_kurtmckee_doc_notify_opts_sc_11450.rst
docs/source/globus_action_providers.rst
examples/action_bodies/transfer.json

This fixes two typos and adds the `notify_on_*` options to the transfer example JSON file.
Documentation
-------------
- Add the ``"notify_on_*"`` parameters to the transfer action provider JSON example.

Add `notify_on_*` options to the transfer example JSON file

---

changelog.d/20220107_173705_uriel_add_example_flow_input_schema.rst
examples/flows/single-transfer/input-schema.json

The Single Transfer Flow definition was missing an input schema. This PR adds its schema.

Adds an input schema sample Flow definition

---

changelog.d/20211221_182204_jimPruyne_caching_and_polling.rst
docs/source/authoring_flows.rst

The discussion of Action polling has been updated to reflect the
current policy.
A new "Note" clarification has been added to describe the policy of
caching token checks and how this may impact a user who rescinds a
consent/token.

Updates to discussion of polling and token caching

---

changelog.d/20220211_164656_kurtmckee_output_login_prompts_stderr.rst
globus_automate_client/cli/auth.py

This protects serialized output, like JSON output, so it can be easily piped to tools like `jq` for further processing.

Write login prompts to STDERR

---

examples/flows/transfer-mv-yaml/sample_input.yaml
examples/flows/transfer-mv/sample_input.json

This is Jim's work. The bugs still exist in `main` so let's review and merge this PR.
Comment from the commit:
>The description says we're going from go#ep1 to go#ep2, but in fact
>the destination endpoint id was not for go#ep2.
>
>Also, the use of the hash in the label is not allowed so changed that
>to an underscore.

Transfer label and destination endpoint incorrect

---

.editorconfig

Now all `.json` files will use 2 spaces.

Standardize JSON files in `.editorconfig`

---

docs/source/cli_docs.rst
globus_automate_client/cli/flows.py

Found these typos while investigating how input schemas are submitted to, and received from, the Flows service.
```diff
- defintion
+ definition
```
```diff
- seperated
+ separated
```
```diff
- hvae
+ have
```

Fix a typo

---

changelog.d/20220307_084347_kurtmckee_fix_tabular_run_list_output.rst
globus_automate_client/cli/flows.py
globus_automate_client/cli/rich_helpers.py
globus_automate_client/flows_client.py
tests/test_flows_client.py

The root cause is that `run-enumerate` and `run-list` anticipate different top-level JSON object keys (`"runs"` and `"actions"`, respectively) but the `run-list` command calls the same function as `run-enumerate` if no `--flow-id` is specified.
The mismatch of anticipated top-level keys prevented `run-list` from finding results to present in tabular form.
Notably, changing the URL route from `.../actions` to `.../runs` changes the top-level key name, too.
JSON and YAML output formats were not affected.

Fix tabular `run-list` output

---

changelog.d/20220315_143000_kurtmckee_batch_run_updates_sc_12888.rst
globus_automate_client/action_client.py
globus_automate_client/cli/callbacks.py
globus_automate_client/cli/flows.py
globus_automate_client/flows_client.py

These changes allow users to set tags and labels on runs (on the initial run and when updating), and to modify batches of runs.
Features
--------
-   [\[sc-13426\]](https://app.shortcut.com/globus/story/13426) Support setting tags when using the ``flow run`` subcommand.
-   Support batch updates of one or more Runs.
-   Support updating tags and labels using the ``flow run-update`` subcommand.
-   Support erasing the list of Run managers and Run monitors using the ``flow run-update`` subcommand.
This can be done by specifying an empty string for the value of the ``--run-manager`` and ``--run-monitor`` options.

Support batch run updates

---

changelog.d/20220310_131513_jimPruyne_timer_cli_named_in_error_string.rst
globus_automate_client/cli/auth.py

This error string is printed when the token cache file doesn't parse
as proper JSON.

Removing reference to 'Timer CLI'

---

.github/workflows/quality.yaml
Makefile
changelog.d/20220408_093928_kurtmckee_dependency_updates.rst
changelog.d/README.rst
globus_automate_client/action_client.py
globus_automate_client/cli/actions.py
globus_automate_client/cli/flows.py
globus_automate_client/cli/rich_helpers.py
globus_automate_client/cli/rich_rendering.py
globus_automate_client/client_helpers.py
globus_automate_client/flows_client.py
poetry.lock
pyproject.toml
tests/test_action_client.py
tests/test_flows_client.py
tox.ini

This introduces several dependency updates, [one of which (click)](https://github.com/pallets/click/issues/1752) contains a security fix. There are other items addressed, see the changelog below for details.
Note: Upgrading typer currently prevents us from keeping typer-cli as a development dependency. There is a temporary hack in the Makefile to mitigate this. The issue is being tracked in tiangolo/typer-cli#50.
Development
-----------
-   Update click to version 8.0.4.
This resolves a security issue.
-   Update typer to version 0.4.1.
-   Update scriv to version 0.14.0.
scriv is a development dependency.
-   Temporarily remove typer-cli as a listed development dependency.
It is still needed when generating the CLI documentation.
-   Add safety as a test environment for local and CI …

Dependency updates

---

changelog.d/20220429_170559_kurtmckee_update_rich.rst
globus_automate_client/cli/rich_helpers.py
globus_automate_client/cli/rich_rendering.py
poetry.lock
pyproject.toml

Development
-------------
-   Update the rich dependency to 0.12.3.
This resolves a dependency conflict between the Globus CLI and the Globus Automate CLI.
Both command line clients can now be installed in the same environment.

Resolve a Globus/Automate CLI dependency conflict

---

changelog.d/20220613_121945_kurtmckee_update_pyjwt.rst
poetry.lock

Bugfixes
--------
-   Update pyjwt to version 2.4.0 to address [CVE-2022-29217](https://nvd.nist.gov/vuln/detail/CVE-2022-29217).

Update pyjwt to 2.4.0

---

changelog.d/20220613_175005_kurtmckee_standardize_options_sc_13892.rst
globus_automate_client/cli/flows.py
globus_automate_client/flows_client.py
globus_automate_client/helpers.py
tests/test_flows_client.py
tests/test_helpers.py

Bugfixes
--------
-   [\[sc-13892\]](https://app.shortcut.com/globus/story/13892)    Standardize flow viewer, starter, and administrator arguments -- and their aliases -- throughout the CLI and API.
Although this change fixes bugs that prevented documented CLI options from working,
it also introduces breaking changes:
*   ``--flow-viewer``, ``--flow-starter``, and ``--flow-administrator`` are the canonical CLI options.
*   The CLI option aliases will continue to work, but the alias behavior has changed:
*   If an alias is used, a warning is written to STDERR.
*   If the canonical option name is combined with one of its aliases,
an error will be written to STDERR and the Automate client will exit.
The exit code will be 1.
*   If more than one of the acceptable aliases is used (like …

Standardize options

---

.github/CODEOWNERS

Adds CODEOWNERS file with explicit github user handles in order to work around limitations when we just rely on the group.

Add explicit github user handles to CODEOWNERS file

---

WORKFLOW.md

This PR updates the workflow documentation to indicate that the final merge into main should originate from "production" rather than a release or hotfix branch.
Signed-off-by: Ada Nikolaidis <ada@globus.org>

Update Workflow Description

---

changelog.d/20220830_105958_nick_fix_web_option_with_parameters.rst
examples/flows/web-option-with-parameters/definition.json

The web-option-with-parameters definition had some invalid, possibly old,
values which would cause the AP to 500 when deployed and run. Removing
these fixes the flow.

Fix example flow definition: web-option-with-parameters

---

docs/source/authoring_flows.rst
docs/source/globus_action_providers.rst

- Adds an entry for the funcX AP with a link back to the funcX docs
- Tweaks the language regarding the `is_managed` fields on the collection info AP
- Fixes a couple small typos in the Authoring Flows section

Update Action Provider Documentation Details

---

changelog.d/20221113_160825_ada_docs_edits.rst
docs/source/authoring_flows.rst
docs/source/cli_docs.rst
docs/source/example_flows.rst
docs/source/globus_action_providers.rst
docs/source/index.rst
docs/source/overview.rst
docs/source/python_sdk_reference.rst
docs/source/quick_start.rst
docs/source/using_the_cli.rst

Includes fixes for uses of “Automate” as well as fixes for capitalization of non-proper nouns and instances where backquotes appear to have been used to indicate emphasis. This is admittedly not comprehensive, so consider this a downpayment on further docs improvements.

Apply an edit pass to fix several docs issues

---

changelog.d/20221115_141348_ada_example_updates.rst
docs/source/authoring_flows.rst

Our production flows are quite complex and could be difficult for a new author to use as a reference when getting started. This adds simplified versions of these flow definitions as inline examples on the “Authoring Flows” page.
For the purposes of this story, I have largely focused on removing the checks that ensure one of the collections is managed (since a non-subscriber user would need to consume their one free deployed flow, we're okay with this as a substitute limitation) and some explicit error handling that provided defaults when the destination does not exist (as a consequence, now allowing the flow definition to present linearly) as well as reordering the steps to make the definitions easier to read sequentially. I highlighted the production flows in a tip above their …

Add simplified inline flow examples to docs

---

.github/CODEOWNERS
pyproject.toml

This allows tools like `tox` to install mandatory dependencies much more quickly (due to only requiring standalone `poetry-core` instead of `poetry` plus all of its many CLI dependencies).

Use poetry-core as the build system

---

changelog.d/20230207_143615_kurtmckee.rst
globus_automate_client/action_client.py
globus_automate_client/cli/flows.py
globus_automate_client/flows_client.py

Features
--------
-   Support retrieval of the flow definition and input schema used to start a run.
This is supported in the new ``flow run-definition`` subcommand.

Support getting the flow definition and schema used to start a run

---

changelog.d/20230314_155142_kurtmckee_prevent_passive_permission_changes_on_flow_update_sc_19291.rst
globus_automate_client/cli/flows.py

Bugfixes
--------
-   [\[sc-19291\]](https://app.shortcut.com/globus/story/19291)    Prevent passive flow permission updates.
Previously, permissions were erased during updates if no permissions were specified.
Now, permissions will only be erased if an empty string is passed. For example:
```text
globus-automate flow update $UUID --flow-viewer=""
```

Prevent passive flow permission updates

---

docs/source/conf.py

This PR introduces a deprecation warning at the top of each HTML page.
It currently renders like this:

Add a deprecation notice to the top of every HTML page

---

docs/source/index.rst
docs/source/migration.rst

This PR should stay in draft until a CLI release provides the features which are currently in `main` and an SDK release contains the Create & Run Flow example.
---
The guide doc covers the following sections:
- map CLI commands (in a table)
- map SDK methods (in a table)
- reshaping YAML into JSON[^1]; loading YAML with pyyaml
- detailed guidance regarding all converted options
- detailed guidance on replacing `create_flows_client`
I have tried to refrain from editorializing or providing more context than is necessarily _useful_ to the user.
The only clear exception to this rule is `create_flows_client`, in which case I felt that we need to justify at some level the apparent loss of functionality -- in fact, replacing troubling functionality with something in which we have more confidence …

Introduce a migration doc for globus-sdk and globus-cli usage replacing this library
